filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        stream: stdout
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log

processors:
  - decode_json_fields:
      fields: ["log", "message"]
      target: ""
      overwrite_keys: true
  - add_docker_metadata: ~
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

setup.ilm.enabled: false

logging.level: debug
logging.to_stdout: true

